SET DEFINE OFF;
DROP TABLE transactions CASCADE CONSTRAINTS;
DROP TABLE recommendations CASCADE CONSTRAINTS;
DROP TABLE category_mappings CASCADE CONSTRAINTS;
DROP TABLE category_keywords CASCADE CONSTRAINTS;
DROP TABLE category_budget_targets CASCADE CONSTRAINTS;
DROP TABLE financial_profile_history CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE currencies CASCADE CONSTRAINTS;

CREATE TABLE currencies (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_currency VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE users (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    monthly_income DECIMAL(19,2),
    saving_frequency VARCHAR(20),
    financial_profile VARCHAR(20),
    profile_accuracy FLOAT,
    profile_updated_at TIMESTAMP
);

CREATE TABLE transactions (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    operation_number VARCHAR(100),
    amount DECIMAL(19,2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    transaction_date DATE NOT NULL,
    currency_id NUMBER(19, 0),
    balance_after DECIMAL(19,2),
    user_id NUMBER(19, 0) NOT NULL,
    source VARCHAR(10) DEFAULT 'BANK',
    payment_method VARCHAR(20),
    link_status VARCHAR(10) DEFAULT 'UNLINKED',
    linked_transaction_id NUMBER(19, 0),
    category_method VARCHAR(20),
    category_confidence FLOAT,
    bank_name VARCHAR(100),
    CONSTRAINT fk_transactions_currency
        FOREIGN KEY (currency_id) REFERENCES currencies (id),
    CONSTRAINT fk_transactions_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_transactions_amount_positive
        CHECK (amount > 0)
);

CREATE TABLE recommendations (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    generated_at TIMESTAMP,
    profile_at_generation VARCHAR(20),
    user_id NUMBER(19, 0) NOT NULL,
    CONSTRAINT fk_recommendations_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Tabla de mapeos colaborativos por retroalimentación (crowdsourcing)
CREATE TABLE category_mappings (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description_pattern VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    frequency INT DEFAULT 1
);

-- Tabla de palabras clave por categoría (reemplaza enum hardcodeado para escalabilidad)
CREATE TABLE category_keywords (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL
);

-- Tabla de metas presupuestarias de referencia por categoría (Encuesta INE)
CREATE TABLE category_budget_targets (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    target_percentage DECIMAL(5,2) NOT NULL,
    country_code VARCHAR(2) DEFAULT 'CL' NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uk_category_country UNIQUE (category, country_code)
);

-- Tabla para el historial de evoluciones de perfil financiero del usuario
CREATE TABLE financial_profile_history (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19, 0) NOT NULL,
    financial_profile VARCHAR(20) NOT NULL,
    profile_accuracy FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_profile_history_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_transactions_user_id ON transactions (user_id);
CREATE INDEX idx_recommendations_user_id ON recommendations (user_id);
CREATE INDEX idx_keywords_category ON category_keywords (category);
CREATE INDEX idx_budget_targets_category ON category_budget_targets (category);
CREATE INDEX idx_profile_history_user_id ON financial_profile_history (user_id);

-- Insert de palabras clave iniciales para la tabla category_keywords
-- ALIMENTACIÓN (FOOD)
INSERT INTO category_keywords (keyword, category) VALUES ('JUMBO', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('LIDER', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('TOTTUS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('UNIMARC', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('SANTA ISABEL', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('MCDONALDS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('MC DONALDS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('BURGER KING', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('PEDIDOSYA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('PEDIDOS YA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('RAPPI', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('UBER EATS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('UBEREATS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('CORNERSHOP', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('SUPERMERCADO', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('ALMACEN', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('CARNICERIA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('VERDULERIA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('RESTAURANT', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('RESTAURANTE', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('CAFE', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('PANADERIA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('PIZZERIA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('STARBUCKS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('DOMINOS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('PAPA JOHNS', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('SUBWAY', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('KFC', 'FOOD');

-- TRANSPORTE (TRANSPORT)
INSERT INTO category_keywords (keyword, category) VALUES ('METRO', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('BIP', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('UBER', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('CABIFY', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('DIDI', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('BEAT', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('COPEC', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('SHELL', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('PETROBRAS', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('ENEX', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('ESTACIONAMIENTO', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('PARKING', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('PEAJE', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('AUTOPISTA', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('LATAM', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('SKY AIRLINE', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('JETSMART', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('BUS', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('PULLMAN', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('TURBUS', 'TRANSPORT');

-- SERVICIOS BASICOS (UTILITIES)
INSERT INTO category_keywords (keyword, category) VALUES ('ENEL', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('AGUAS ANDINAS', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('ESSBIO', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('AGUAS DEL VALLE', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('VTR', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('MOVISTAR', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('CLARO', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('ENTEL', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('WOM', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('METROGAS', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('ABASTIBLE', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('LIPIGAS', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('GASCO', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('CGE', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('CHILQUINTA', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('SAESA', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('TELEFONO', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('INTERNET', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('LUZ', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('AGUA', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('GAS', 'UTILITIES');

-- SALUD (HEALTH)
INSERT INTO category_keywords (keyword, category) VALUES ('CRUZ VERDE', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('AHUMADA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('SALCOBRAND', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('CLINICA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('HOSPITAL', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('MEDICO', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('DOCTOR', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('FARMACIA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('LABORATORIO', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('DENTAL', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('DENTISTA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('FONASA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('ISAPRE', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('COLMENA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('BANMEDICA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('CONSULTA MEDICA', 'HEALTH');

-- VIVIENDA (HOUSING)
INSERT INTO category_keywords (keyword, category) VALUES ('GASTO COMUN', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('GASTOS COMUNES', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('ARRIENDO', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('ALQUILER', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('DIVIDENDO', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('HIPOTECARIO', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('PORTALINMOBILIARIO', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('INMOBILIARIA', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('CONDOMINIO', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('ADMINISTRACION EDIFICIO', 'HOUSING');

-- EDUCACION (EDUCATION)
INSERT INTO category_keywords (keyword, category) VALUES ('COLEGIO', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('UNIVERSIDAD', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('DUOC', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('INACAP', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('AIEP', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('UDEMY', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('COURSERA', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('PLATZI', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('DOMESTIKA', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('MATRICULA', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('ARANCEL', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('ESCUELA', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('INSTITUTO', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('LIBRERIA', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('LIBRO', 'EDUCATION');

-- ENTRETENIMIENTO (ENTERTAINMENT)
INSERT INTO category_keywords (keyword, category) VALUES ('NETFLIX', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('SPOTIFY', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('DISNEY', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('YOUTUBE PREMIUM', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('HBO', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('AMAZON PRIME', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('APPLE TV', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('PARAMOUNT', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('CINE', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('CINEMARK', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('CINEPLANET', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('CINEPOLIS', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('TEATRO', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('CONCIERTO', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('EVENTO', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('PLAYSTATION', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('XBOX', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('STEAM', 'ENTERTAINMENT');
INSERT INTO category_keywords (keyword, category) VALUES ('NINTENDO', 'ENTERTAINMENT');

-- COMPRAS (SHOPPING)
INSERT INTO category_keywords (keyword, category) VALUES ('FALABELLA', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('RIPLEY', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('PARIS', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('ZARA', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('H&M', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('FOREVER', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('MERCADOLIBRE', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('MERCADO LIBRE', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('AMAZON', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('ALIEXPRESS', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('SHEIN', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('SODIMAC', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('HOMECENTER', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('EASY', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('IKEA', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('TIENDA', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('MALL', 'SHOPPING');
INSERT INTO category_keywords (keyword, category) VALUES ('OUTLET', 'SHOPPING');

-- SALARIO / SUELDO (SALARY)
INSERT INTO category_keywords (keyword, category) VALUES ('SUELDO', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('REMUNERACION', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('REMUNERACIONES', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('HONORARIO', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('HONORARIOS', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('NOMINA', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('SALARIO', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('LIQUIDACION SUELDO', 'SALARY');


-- =============================================================================
-- DATOS DUMMY DE PRUEBA (SEED DATA)
-- =============================================================================

-- 1. Insert de monedas principales de LATAM, Dólar y Euro
INSERT INTO currencies (name_currency) VALUES ('USD'); -- Dólar Estadounidense
INSERT INTO currencies (name_currency) VALUES ('EUR'); -- Euro
INSERT INTO currencies (name_currency) VALUES ('CLP'); -- Peso Chileno
INSERT INTO currencies (name_currency) VALUES ('ARS'); -- Peso Argentino
INSERT INTO currencies (name_currency) VALUES ('MXN'); -- Peso Mexicano
INSERT INTO currencies (name_currency) VALUES ('COP'); -- Peso Colombiano
INSERT INTO currencies (name_currency) VALUES ('PEN'); -- Sol Peruano
INSERT INTO currencies (name_currency) VALUES ('BRL'); -- Real Brasileño
INSERT INTO currencies (name_currency) VALUES ('UYU'); -- Peso Uruguayo
INSERT INTO currencies (name_currency) VALUES ('DOP'); -- Peso Dominicano
INSERT INTO currencies (name_currency) VALUES ('CRC'); -- Colón Costarricense
INSERT INTO currencies (name_currency) VALUES ('GTQ'); -- Quetzal Guatemalteco
INSERT INTO currencies (name_currency) VALUES ('PYG'); -- Guaraní Paraguayo
INSERT INTO currencies (name_currency) VALUES ('BOB'); -- Boliviano
INSERT INTO currencies (name_currency) VALUES ('HNL'); -- Lempira Hondureño
INSERT INTO currencies (name_currency) VALUES ('NIO'); -- Córdoba Nicaragüense
INSERT INTO currencies (name_currency) VALUES ('VES'); -- Bolívar Venezolano
INSERT INTO currencies (name_currency) VALUES ('PAB'); -- Balboa Panameño


-- 2. Insert de usuarios dummy (Contraseña para todos: password123)
INSERT INTO users (name, email, password, monthly_income, saving_frequency, financial_profile, profile_accuracy, profile_updated_at) VALUES ('Juan Pérez', 'juan.perez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 2500000.00, 'MONTHLY', 'SAVER', 0.85, CURRENT_TIMESTAMP);
INSERT INTO users (name, email, password, monthly_income, saving_frequency, financial_profile, profile_accuracy, profile_updated_at) VALUES ('María González', 'maria.gonzalez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 1800000.00, 'BIWEEKLY', 'BALANCED', 0.78, CURRENT_TIMESTAMP);
INSERT INTO users (name, email, password, monthly_income, saving_frequency, financial_profile, profile_accuracy, profile_updated_at) VALUES ('Carlos Rodríguez', 'carlos.rodriguez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 950000.00, 'RARELY', 'SPENDER', 0.90, CURRENT_TIMESTAMP);
INSERT INTO users (name, email, password, monthly_income, saving_frequency, financial_profile, profile_accuracy, profile_updated_at) VALUES ('Ana Martínez', 'ana.martinez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 600000.00, 'NEVER', 'AT_RISK', 0.95, CURRENT_TIMESTAMP);
INSERT INTO users (name, email, password, monthly_income, saving_frequency, financial_profile, profile_accuracy, profile_updated_at) VALUES ('Lucas Silva', 'lucas.silva@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 3200000.00, 'WEEKLY', 'SAVER', 0.88, CURRENT_TIMESTAMP);


-- 3. Insert de transacciones dummy
-- Usuario 1 (Juan - Chile CLP)
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('SUELDO EMPRESA TECH', 'OP-1001', 2500000.00, 'SALARY', DATE '2026-08-01', 3, 2500000.00, 1);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('GASTO COMUN EDIFICIO', 'OP-1002', 120000.00, 'HOUSING', DATE '2026-08-02', 3, 2380000.00, 1);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('SUPERMERCADO JUMBO', 'OP-1003', 85000.50, 'FOOD', DATE '2026-08-03', 3, 2294999.50, 1);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('PAGO LUZ ENEL', 'OP-1004', 35000.00, 'UTILITIES', DATE '2026-08-04', 3, 2259999.50, 1);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('NETFLIX SUBSCRIPTION', 'OP-1005', 10990.00, 'ENTERTAINMENT', DATE '2026-08-05', 3, 2249009.50, 1);

-- Usuario 2 (María - México MXN)
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('NOMINA MENSUAL', 'OP-2001', 35000.00, 'SALARY', DATE '2026-08-01', 5, 35000.00, 2);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('ALQUILER DEPARTAMENTO', 'OP-2002', 12000.00, 'HOUSING', DATE '2026-08-02', 5, 23000.00, 2);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('COMPRAS MERCADO LIBRE', 'OP-2003', 1500.00, 'SHOPPING', DATE '2026-08-03', 5, 21500.00, 2);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('RESTAURANTE BURGER KING', 'OP-2004', 450.00, 'FOOD', DATE '2026-08-04', 5, 21050.00, 2);

-- Usuario 3 (Carlos - USD / Internacional)
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('REMUNERACION FREELANCE', 'OP-3001', 1200.00, 'SALARY', DATE '2026-08-01', 1, 1200.00, 3);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('UBER TRIPS', 'OP-3002', 45.00, 'TRANSPORT', DATE '2026-08-02', 1, 1155.00, 3);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('PLATZI SUSCRIPCION', 'OP-3003', 25.00, 'EDUCATION', DATE '2026-08-03', 1, 1130.00, 3);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('FARMACIA CRUZ VERDE', 'OP-3004', 60.00, 'HEALTH', DATE '2026-08-04', 1, 1070.00, 3);

-- Usuario 4 (Ana - Colombia COP)
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('SALARIO MENSUAL', 'OP-4001', 2400000.00, 'SALARY', DATE '2026-08-01', 6, 2400000.00, 4);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('SUPERMERCADO EXITO', 'OP-4002', 350000.00, 'FOOD', DATE '2026-08-02', 6, 2050000.00, 4);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('PAGO SERVICIO SERVIUDAD', 'OP-4003', 180000.00, 'UTILITIES', DATE '2026-08-03', 6, 1870000.00, 4);

-- Usuario 5 (Lucas - Euro EUR)
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('PAYROLL DEPOSIT', 'OP-5001', 3200.00, 'SALARY', DATE '2026-08-01', 2, 3200.00, 5);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('AMAZON PRIME', 'OP-5002', 49.99, 'ENTERTAINMENT', DATE '2026-08-02', 2, 3150.01, 5);
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES ('SPOTIFY FAMILY', 'OP-5003', 17.99, 'ENTERTAINMENT', DATE '2026-08-03', 2, 3132.02, 5);


-- 4. Insert de recomendaciones dummy
INSERT INTO recommendations (text, generated_at, profile_at_generation, user_id) VALUES ('Felicidades por mantener una tasa de ahorro constante. Te recomendamos diversificar en un fondo indexado.', CURRENT_TIMESTAMP, 'SAVER', 1);
INSERT INTO recommendations (text, generated_at, profile_at_generation, user_id) VALUES ('Tus gastos en entretenimiento representan un 15% de tus ingresos. Reducirlos un 5% aumentará tu fondo de emergencia.', CURRENT_TIMESTAMP, 'BALANCED', 2);
INSERT INTO recommendations (text, generated_at, profile_at_generation, user_id) VALUES ('Detectamos un alto gasto en transporte privado. Considera usar transporte público o compartido para optimizar presupuesto.', CURRENT_TIMESTAMP, 'SPENDER', 3);
INSERT INTO recommendations (text, generated_at, profile_at_generation, user_id) VALUES ('Atención: Tus gastos fijos superan el 80% de tus ingresos mensuales. Se sugiere revisar suscripciones y compras secundarias.', CURRENT_TIMESTAMP, 'AT_RISK', 4);
INSERT INTO recommendations (text, generated_at, profile_at_generation, user_id) VALUES ('Excelente gestión financiera. Tienes capacidad de ahorro semanal activa.', CURRENT_TIMESTAMP, 'SAVER', 5);


-- 5. Insert de mapeos colaborativos dummy (crowdsourcing)
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PATRON_JUMBO_EXPRESS', 'FOOD', 5);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PATRON_UBER_EATS_APP', 'FOOD', 12);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PATRON_CABIFY_RIDE', 'TRANSPORT', 8);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PATRON_SPOTIFY_MONTHLY', 'ENTERTAINMENT', 15);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PATRON_FARMACIAS_AHUMADA', 'HEALTH', 4);


-- =============================================================================
-- DATOS DE CATEGORÍAS Y PRESUPUESTOS (CONTEXTO: CHILE)
-- =============================================================================

-- 5. Objetivos de Presupuesto por Categoría (Chile - CL)
-- Porcentajes sugeridos basados en la regla 50/30/20 adaptada.
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('HOUSING', 30.00, 'CL', 'Vivienda: Arriendo o dividendo, contribuciones y gastos comunes');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('FOOD', 15.00, 'CL', 'Alimentación: Supermercados, ferias y almacenes');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('TRANSPORT', 10.00, 'CL', 'Transporte: Tarjeta Bip!, bencina, TAG, Metro y aplicaciones (Uber/Cabify)');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('UTILITIES', 8.00, 'CL', 'Servicios Básicos: Luz, agua, gas, internet hogar y telefonía móvil');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('HEALTH', 5.00, 'CL', 'Salud: Farmacias, bonos Fonasa/Isapre, consultas y exámenes');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('EDUCATION', 10.00, 'CL', 'Educación: Matrículas, mensualidades de colegios/universidades (CAE) y materiales');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('ENTERTAINMENT', 5.00, 'CL', 'Entretenimiento: Streaming (Netflix/Spotify), cine, restaurantes y salidas');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('SAVINGS', 10.00, 'CL', 'Ahorro: Cuentas de ahorro, depósitos a plazo, APV, fondos mutuos');
INSERT INTO category_budget_targets (category, target_percentage, country_code, description) VALUES ('OTHER_EXPENSE', 7.00, 'CL', 'Deudas: Cuotas de tarjetas de crédito, líneas de crédito y préstamos de consumo');



-- 6. Mapeo de Patrones de Transacciones (Comercios y servicios chilenos)
-- Supermercados / Alimentación
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('LIDER', 'FOOD', 100);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('JUMBO', 'FOOD', 80);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('UNIMARC', 'FOOD', 70);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('SANTA ISABEL', 'FOOD', 60);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('TOTTUS', 'FOOD', 50);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PEDIDOSYA', 'FOOD', 90);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('RAPPI', 'FOOD', 85);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('MAYORISTA 10', 'FOOD', 40);

-- Servicios Básicos (Agua, Luz, Gas, Telecomunicaciones)
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('ENEL', 'UTILITIES', 95);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CGE', 'UTILITIES', 80);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('AGUAS ANDINAS', 'UTILITIES', 95);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('ESVAL', 'UTILITIES', 40);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('ESSBIO', 'UTILITIES', 30);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('METROGAS', 'UTILITIES', 85);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('ABASTIBLE', 'UTILITIES', 60);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('LIPOIGAS', 'UTILITIES', 60);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('GASCO', 'UTILITIES', 50);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('VTR', 'UTILITIES', 90);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('ENTEL', 'UTILITIES', 95);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('MOVISTAR', 'UTILITIES', 95);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('WOM', 'UTILITIES', 80);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CLARO', 'UTILITIES', 70);

-- Transporte
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('METRO SA', 'TRANSPORT', 100);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CARGA BIP', 'TRANSPORT', 100);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('AUTOPISTA', 'TRANSPORT', 80);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('COSTANERA NORTE', 'TRANSPORT', 75);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('VESPUCIO SUR', 'TRANSPORT', 70);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('VESPUCIO NORTE', 'TRANSPORT', 70);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('COPEC', 'TRANSPORT', 90);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('SHELL', 'TRANSPORT', 85);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PETROBRAS', 'TRANSPORT', 70);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('UBER', 'TRANSPORT', 95);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CABIFY', 'TRANSPORT', 80);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('DIDI', 'TRANSPORT', 60);

-- Salud
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CRUZ VERDE', 'HEALTH', 90);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('SALCOBRAND', 'HEALTH', 85);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('FARMACIAS AHUMADA', 'HEALTH', 80);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('DR SIMI', 'HEALTH', 75);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('INTEGRAMEDICA', 'HEALTH', 60);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('RED SALUD', 'HEALTH', 50);

-- Retail / Vestuario y Hogar
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('FALABELLA', 'SHOPPING', 80);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PARIS', 'SHOPPING', 75);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('RIPLEY', 'SHOPPING', 75);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CENCOSUD', 'SHOPPING', 70);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('H&M', 'SHOPPING', 60);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('ZARA', 'SHOPPING', 50);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CASAIDEAS', 'HOUSING', 60);

-- Entretenimiento
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('NETFLIX', 'ENTERTAINMENT', 95);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('SPOTIFY', 'ENTERTAINMENT', 90);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CINEHOYTS', 'ENTERTAINMENT', 60);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('CINEMARK', 'ENTERTAINMENT', 60);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('PUNTO TICKET', 'ENTERTAINMENT', 50);
INSERT INTO category_mappings (description_pattern, category, frequency) VALUES ('TICKETMASTER', 'ENTERTAINMENT', 40);



-- 7. Palabras Clave para Categorización Automática (Terminología chilena)
-- Vivienda
INSERT INTO category_keywords (keyword, category) VALUES ('GGCC', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('CONSERJE', 'HOUSING');
INSERT INTO category_keywords (keyword, category) VALUES ('CONTRIBUCIONES', 'HOUSING');

-- Alimentación
INSERT INTO category_keywords (keyword, category) VALUES ('BOTILLERIA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('FERIA', 'FOOD');
INSERT INTO category_keywords (keyword, category) VALUES ('COLACION', 'FOOD');

-- Transporte
INSERT INTO category_keywords (keyword, category) VALUES ('MICRO', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('BENCINA', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('TAG', 'TRANSPORT');
INSERT INTO category_keywords (keyword, category) VALUES ('PASAJES', 'TRANSPORT');

-- Servicios Básicos
INSERT INTO category_keywords (keyword, category) VALUES ('PLAN CELULAR', 'UTILITIES');
INSERT INTO category_keywords (keyword, category) VALUES ('RECARGA', 'UTILITIES');

-- Salud
INSERT INTO category_keywords (keyword, category) VALUES ('BONO FONASA', 'HEALTH');
INSERT INTO category_keywords (keyword, category) VALUES ('REMEDIOS', 'HEALTH');

-- Educación
INSERT INTO category_keywords (keyword, category) VALUES ('CAE', 'EDUCATION');
INSERT INTO category_keywords (keyword, category) VALUES ('MENSUALIDAD', 'EDUCATION');

-- Ingresos
INSERT INTO category_keywords (keyword, category) VALUES ('AGUINALDO', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('ANTICIPO', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('BOLETA', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('PENSION', 'SALARY');
INSERT INTO category_keywords (keyword, category) VALUES ('FINIQUITO', 'SALARY');

COMMIT;