CREATE TABLE currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_currency VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    monthly_income DECIMAL(19,2),
    saving_frequency VARCHAR(20),
    financial_profile VARCHAR(20),
    profile_accuracy DOUBLE,
    profile_updated_at TIMESTAMP
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    operation_number VARCHAR(100),
    amount DECIMAL(19,2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    transaction_date DATE NOT NULL,
    currency_id BIGINT,
    balance_after DECIMAL(19,2),
    user_id BIGINT NOT NULL,
    source VARCHAR(10) DEFAULT 'BANK',
    payment_method VARCHAR(20),
    link_status VARCHAR(10) DEFAULT 'UNLINKED',
    linked_transaction_id BIGINT,
    category_method VARCHAR(20),
    category_confidence DOUBLE,
    bank_name VARCHAR(100),
    CONSTRAINT fk_transactions_currency
        FOREIGN KEY (currency_id) REFERENCES currencies (id),
    CONSTRAINT fk_transactions_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_transactions_amount_positive
        CHECK (amount > 0)
);

CREATE TABLE recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    generated_at TIMESTAMP,
    profile_at_generation VARCHAR(20),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_recommendations_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Tabla de mapeos colaborativos por retroalimentación (crowdsourcing)
CREATE TABLE transaction_category_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description_pattern VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    frequency INT DEFAULT 1
);

-- Tabla de palabras clave por categoría (reemplaza enum hardcodeado para escalabilidad)
CREATE TABLE category_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL
);

-- Tabla de metas presupuestarias de referencia por categoría (Encuesta INE)
CREATE TABLE category_budget_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    target_percentage DECIMAL(5,2) NOT NULL,
    country_code VARCHAR(2) NOT NULL DEFAULT 'CL',
    description VARCHAR(255),
    CONSTRAINT uk_category_country UNIQUE (category, country_code)
);

-- Tabla para el historial de evoluciones de perfil financiero del usuario
CREATE TABLE financial_profile_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    financial_profile VARCHAR(20) NOT NULL,
    profile_accuracy DOUBLE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_profile_history_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_transactions_user_id ON transactions (user_id);
CREATE INDEX idx_recommendations_user_id ON recommendations (user_id);
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_mappings_pattern ON transaction_category_mappings (description_pattern);
CREATE INDEX idx_keywords_category ON category_keywords (category);
CREATE INDEX idx_budget_targets_category ON category_budget_targets (category);
CREATE INDEX idx_profile_history_user_id ON financial_profile_history (user_id);


-- Insert de palabras clave iniciales para la tabla category_keywords
INSERT INTO category_keywords (keyword, category) VALUES
-- ALIMENTACIÓN (FOOD)
('JUMBO', 'FOOD'),
('LIDER', 'FOOD'),
('TOTTUS', 'FOOD'),
('UNIMARC', 'FOOD'),
('SANTA ISABEL', 'FOOD'),
('MCDONALDS', 'FOOD'),
('MC DONALDS', 'FOOD'),
('BURGER KING', 'FOOD'),
('PEDIDOSYA', 'FOOD'),
('PEDIDOS YA', 'FOOD'),
('RAPPI', 'FOOD'),
('UBER EATS', 'FOOD'),
('UBEREATS', 'FOOD'),
('CORNERSHOP', 'FOOD'),
('SUPERMERCADO', 'FOOD'),
('ALMACEN', 'FOOD'),
('CARNICERIA', 'FOOD'),
('VERDULERIA', 'FOOD'),
('RESTAURANT', 'FOOD'),
('RESTAURANTE', 'FOOD'),
('CAFE', 'FOOD'),
('PANADERIA', 'FOOD'),
('PIZZERIA', 'FOOD'),
('STARBUCKS', 'FOOD'),
('DOMINOS', 'FOOD'),
('PAPA JOHNS', 'FOOD'),
('SUBWAY', 'FOOD'),
('KFC', 'FOOD'),

-- TRANSPORTE (TRANSPORT)
('METRO', 'TRANSPORT'),
('BIP', 'TRANSPORT'),
('UBER', 'TRANSPORT'),
('CABIFY', 'TRANSPORT'),
('DIDI', 'TRANSPORT'),
('BEAT', 'TRANSPORT'),
('COPEC', 'TRANSPORT'),
('SHELL', 'TRANSPORT'),
('PETROBRAS', 'TRANSPORT'),
('ENEX', 'TRANSPORT'),
('ESTACIONAMIENTO', 'TRANSPORT'),
('PARKING', 'TRANSPORT'),
('PEAJE', 'TRANSPORT'),
('AUTOPISTA', 'TRANSPORT'),
('LATAM', 'TRANSPORT'),
('SKY AIRLINE', 'TRANSPORT'),
('JETSMART', 'TRANSPORT'),
('BUS', 'TRANSPORT'),
('PULLMAN', 'TRANSPORT'),
('TURBUS', 'TRANSPORT'),

-- SERVICIOS BASICOS (UTILITIES)
('ENEL', 'UTILITIES'),
('AGUAS ANDINAS', 'UTILITIES'),
('ESSBIO', 'UTILITIES'),
('AGUAS DEL VALLE', 'UTILITIES'),
('VTR', 'UTILITIES'),
('MOVISTAR', 'UTILITIES'),
('CLARO', 'UTILITIES'),
('ENTEL', 'UTILITIES'),
('WOM', 'UTILITIES'),
('METROGAS', 'UTILITIES'),
('ABASTIBLE', 'UTILITIES'),
('LIPIGAS', 'UTILITIES'),
('GASCO', 'UTILITIES'),
('CGE', 'UTILITIES'),
('CHILQUINTA', 'UTILITIES'),
('SAESA', 'UTILITIES'),
('TELEFONO', 'UTILITIES'),
('INTERNET', 'UTILITIES'),
('LUZ', 'UTILITIES'),
('AGUA', 'UTILITIES'),
('GAS', 'UTILITIES'),

-- SALUD (HEALTH)
('CRUZ VERDE', 'HEALTH'),
('AHUMADA', 'HEALTH'),
('SALCOBRAND', 'HEALTH'),
('CLINICA', 'HEALTH'),
('HOSPITAL', 'HEALTH'),
('MEDICO', 'HEALTH'),
('DOCTOR', 'HEALTH'),
('FARMACIA', 'HEALTH'),
('LABORATORIO', 'HEALTH'),
('DENTAL', 'HEALTH'),
('DENTISTA', 'HEALTH'),
('FONASA', 'HEALTH'),
('ISAPRE', 'HEALTH'),
('COLMENA', 'HEALTH'),
('BANMEDICA', 'HEALTH'),
('CONSULTA MEDICA', 'HEALTH'),

-- VIVIENDA (HOUSING)
('GASTO COMUN', 'HOUSING'),
('GASTOS COMUNES', 'HOUSING'),
('ARRIENDO', 'HOUSING'),
('ALQUILER', 'HOUSING'),
('DIVIDENDO', 'HOUSING'),
('HIPOTECARIO', 'HOUSING'),
('PORTALINMOBILIARIO', 'HOUSING'),
('INMOBILIARIA', 'HOUSING'),
('CONDOMINIO', 'HOUSING'),
('ADMINISTRACION EDIFICIO', 'HOUSING'),

-- EDUCACION (EDUCATION)
('COLEGIO', 'EDUCATION'),
('UNIVERSIDAD', 'EDUCATION'),
('DUOC', 'EDUCATION'),
('INACAP', 'EDUCATION'),
('AIEP', 'EDUCATION'),
('UDEMY', 'EDUCATION'),
('COURSERA', 'EDUCATION'),
('PLATZI', 'EDUCATION'),
('DOMESTIKA', 'EDUCATION'),
('MATRICULA', 'EDUCATION'),
('ARANCEL', 'EDUCATION'),
('ESCUELA', 'EDUCATION'),
('INSTITUTO', 'EDUCATION'),
('LIBRERIA', 'EDUCATION'),
('LIBRO', 'EDUCATION'),

-- ENTRETENIMIENTO (ENTERTAINMENT)
('NETFLIX', 'ENTERTAINMENT'),
('SPOTIFY', 'ENTERTAINMENT'),
('DISNEY', 'ENTERTAINMENT'),
('YOUTUBE PREMIUM', 'ENTERTAINMENT'),
('HBO', 'ENTERTAINMENT'),
('AMAZON PRIME', 'ENTERTAINMENT'),
('APPLE TV', 'ENTERTAINMENT'),
('PARAMOUNT', 'ENTERTAINMENT'),
('CINE', 'ENTERTAINMENT'),
('CINEMARK', 'ENTERTAINMENT'),
('CINEPLANET', 'ENTERTAINMENT'),
('CINEPOLIS', 'ENTERTAINMENT'),
('TEATRO', 'ENTERTAINMENT'),
('CONCIERTO', 'ENTERTAINMENT'),
('EVENTO', 'ENTERTAINMENT'),
('PLAYSTATION', 'ENTERTAINMENT'),
('XBOX', 'ENTERTAINMENT'),
('STEAM', 'ENTERTAINMENT'),
('NINTENDO', 'ENTERTAINMENT'),

-- COMPRAS (SHOPPING)
('FALABELLA', 'SHOPPING'),
('RIPLEY', 'SHOPPING'),
('PARIS', 'SHOPPING'),
('ZARA', 'SHOPPING'),
('HM', 'SHOPPING'),
('FOREVER', 'SHOPPING'),
('MERCADOLIBRE', 'SHOPPING'),
('MERCADO LIBRE', 'SHOPPING'),
('AMAZON', 'SHOPPING'),
('ALIEXPRESS', 'SHOPPING'),
('SHEIN', 'SHOPPING'),
('SODIMAC', 'SHOPPING'),
('HOMECENTER', 'SHOPPING'),
('EASY', 'SHOPPING'),
('IKEA', 'SHOPPING'),
('TIENDA', 'SHOPPING'),
('MALL', 'SHOPPING'),
('OUTLET', 'SHOPPING'),

-- SALARIO / SUELDO (SALARY)
('SUELDO', 'SALARY'),
('REMUNERACION', 'SALARY'),
('REMUNERACIONES', 'SALARY'),
('HONORARIO', 'SALARY'),
('HONORARIOS', 'SALARY'),
('NOMINA', 'SALARY'),
('SALARIO', 'SALARY'),
('LIQUIDACION SUELDO', 'SALARY');

-- =============================================================================
-- DATOS DUMMY DE PRUEBA (SEED DATA)
-- =============================================================================

-- 1. Insert de monedas principales de LATAM, Dólar y Euro
INSERT INTO currencies (name_currency) VALUES
('USD'), -- Dólar Estadounidense
('EUR'), -- Euro
('CLP'), -- Peso Chileno
('ARS'), -- Peso Argentino
('MXN'), -- Peso Mexicano
('COP'), -- Peso Colombiano
('PEN'), -- Sol Peruano
('BRL'), -- Real Brasileño
('UYU'), -- Peso Uruguayo
('DOP'), -- Peso Dominicano
('CRC'), -- Colón Costarricense
('GTQ'), -- Quetzal Guatemalteco
('PYG'), -- Guaraní Paraguayo
('BOB'), -- Boliviano
('HNL'), -- Lempira Hondureño
('NIO'), -- Córdoba Nicaragüense
('VES'), -- Bolívar Venezolano
('PAB'); -- Balboa Panameño

-- 2. Insert de usuarios dummy (Contraseña para todos: password123)
INSERT INTO users (name, email, password, monthly_income, saving_frequency, financial_profile, profile_accuracy, profile_updated_at) VALUES
('Juan Pérez', 'juan.perez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 2500000.00, 'MONTHLY', 'SAVER', 0.85, CURRENT_TIMESTAMP),
('María González', 'maria.gonzalez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 1800000.00, 'BIWEEKLY', 'BALANCED', 0.78, CURRENT_TIMESTAMP),
('Carlos Rodríguez', 'carlos.rodriguez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 950000.00, 'RARELY', 'SPENDER', 0.90, CURRENT_TIMESTAMP),
('Ana Martínez', 'ana.martinez@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 600000.00, 'NEVER', 'AT_RISK', 0.95, CURRENT_TIMESTAMP),
('Lucas Silva', 'lucas.silva@example.com', '$2a$10$UurvK/egFzuLq7ngVAB6u.4NDhH/r1PVvbCmZGhfpZPhyUL4vMozi', 3200000.00, 'WEEKLY', 'SAVER', 0.88, CURRENT_TIMESTAMP);

-- 3. Insert de transacciones dummy
INSERT INTO transactions (description, operation_number, amount, category, transaction_date, currency_id, balance_after, user_id) VALUES
-- Usuario 1 (Juan - Chile CLP)
('SUELDO EMPRESA TECH', 'OP-1001', 2500000.00, 'SALARY', '2026-08-01', 3, 2500000.00, 1),
('GASTO COMUN EDIFICIO', 'OP-1002', 120000.00, 'HOUSING', '2026-08-02', 3, 2380000.00, 1),
('SUPERMERCADO JUMBO', 'OP-1003', 85000.50, 'FOOD', '2026-08-03', 3, 2294999.50, 1),
('PAGO LUZ ENEL', 'OP-1004', 35000.00, 'UTILITIES', '2026-08-04', 3, 2259999.50, 1),
('NETFLIX SUBSCRIPTION', 'OP-1005', 10990.00, 'ENTERTAINMENT', '2026-08-05', 3, 2249009.50, 1),

-- Usuario 2 (María - México MXN)
('NOMINA MENSUAL', 'OP-2001', 35000.00, 'SALARY', '2026-08-01', 5, 35000.00, 2),
('ALQUILER DEPARTAMENTO', 'OP-2002', 12000.00, 'HOUSING', '2026-08-02', 5, 23000.00, 2),
('COMPRAS MERCADO LIBRE', 'OP-2003', 1500.00, 'SHOPPING', '2026-08-03', 5, 21500.00, 2),
('RESTAURANTE BURGER KING', 'OP-2004', 450.00, 'FOOD', '2026-08-04', 5, 21050.00, 2),

-- Usuario 3 (Carlos - USD / Internacional)
('REMUNERACION FREELANCE', 'OP-3001', 1200.00, 'SALARY', '2026-08-01', 1, 1200.00, 3),
('UBER TRIPS', 'OP-3002', 45.00, 'TRANSPORT', '2026-08-02', 1, 1155.00, 3),
('PLATZI SUSCRIPCION', 'OP-3003', 25.00, 'EDUCATION', '2026-08-03', 1, 1130.00, 3),
('FARMACIA CRUZ VERDE', 'OP-3004', 60.00, 'HEALTH', '2026-08-04', 1, 1070.00, 3),

-- Usuario 4 (Ana - Colombia COP)
('SALARIO MENSUAL', 'OP-4001', 2400000.00, 'SALARY', '2026-08-01', 6, 2400000.00, 4),
('SUPERMERCADO EXITO', 'OP-4002', 350000.00, 'FOOD', '2026-08-02', 6, 2050000.00, 4),
('PAGO SERVICIO SERVIUDAD', 'OP-4003', 180000.00, 'UTILITIES', '2026-08-03', 6, 1870000.00, 4),

-- Usuario 5 (Lucas - Euro EUR)
('PAYROLL DEPOSIT', 'OP-5001', 3200.00, 'SALARY', '2026-08-01', 2, 3200.00, 5),
('AMAZON PRIME', 'OP-5002', 49.99, 'ENTERTAINMENT', '2026-08-02', 2, 3150.01, 5),
('SPOTIFY FAMILY', 'OP-5003', 17.99, 'ENTERTAINMENT', '2026-08-03', 2, 3132.02, 5);

-- 4. Insert de recomendaciones dummy
INSERT INTO recommendations (text, generated_at, profile_at_generation, user_id) VALUES
('Felicidades por mantener una tasa de ahorro constante. Te recomendamos diversificar en un fondo indexado.', CURRENT_TIMESTAMP, 'SAVER', 1),
('Tus gastos en entretenimiento representan un 15% de tus ingresos. Reducirlos un 5% aumentará tu fondo de emergencia.', CURRENT_TIMESTAMP, 'BALANCED', 2),
('Detectamos un alto gasto en transporte privado. Considera usar transporte público o compartido para optimizar presupuesto.', CURRENT_TIMESTAMP, 'SPENDER', 3),
('Atención: Tus gastos fijos superan el 80% de tus ingresos mensuales. Se sugiere revisar suscripciones y compras secundarias.', CURRENT_TIMESTAMP, 'AT_RISK', 4),
('Excelente gestión financiera. Tienes capacidad de ahorro semanal activa.', CURRENT_TIMESTAMP, 'SAVER', 5);

-- 5. Insert de mapeos colaborativos dummy (crowdsourcing)
INSERT INTO transaction_category_mappings (description_pattern, category, frequency) VALUES
('PATRON_JUMBO_EXPRESS', 'FOOD', 5),
('PATRON_UBER_EATS_APP', 'FOOD', 12),
('PATRON_CABIFY_RIDE', 'TRANSPORT', 8),
('PATRON_SPOTIFY_MONTHLY', 'ENTERTAINMENT', 15),
('PATRON_FARMACIAS_AHUMADA', 'HEALTH', 4);