CREATE TABLE currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_currency VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    monthly_income DECIMAL(19,2),
    saving_frequency VARCHAR(20),
    financial_profile VARCHAR(20),
    profile_accuracy DOUBLE,
    profile_updated_at TIMESTAMP
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    operation_number VARCHAR(100),
    amount DECIMAL(19,2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    transaction_date DATE NOT NULL,
    currency_id BIGINT,
    balance_after DECIMAL(19,2),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_transactions_currency
        FOREIGN KEY (currency_id) REFERENCES currencies (id),
    CONSTRAINT fk_transactions_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_transactions_amount_positive
        CHECK (amount > 0)
);

CREATE TABLE recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    generated_at TIMESTAMP,
    profile_at_generation VARCHAR(20),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_recommendations_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_transactions_user_id ON transactions (user_id);
CREATE INDEX idx_recommendations_user_id ON recommendations (user_id);
CREATE INDEX idx_users_email ON users (email);