-- =====================================================================
-- Finance AI — Migración incremental #002
-- Aplica DESPUÉS de db/oracle/schema.sql + db/oracle/data.sql (los reales).
-- No reemplaza ni reescribe nada -- solo agrega columnas a `transactions`
-- y una tabla nueva e independiente (`category_budget_targets`).
--
-- Motivo: Category.java/TransactionType.java NO se tocan (decisión del
-- equipo: nos adaptamos al backend real, no al revés). Las transferencias
-- se detectan por texto en la descripción, no por una categoría nueva --
-- ver BudgetRecommendationService.isLikelyTransfer().
-- =====================================================================

-- 1. Permitir categoría nula en transacciones BANK recién ingeridas, antes
--    de que el clasificador (a implementar) la complete.
ALTER TABLE transactions MODIFY (category NULL);

-- 2. Campos del aporte: origen, medio de pago, conciliación, trazabilidad
--    de clasificación.
ALTER TABLE transactions ADD (
    source                  VARCHAR2(10 CHAR) DEFAULT 'BANK' NOT NULL,
    payment_method          VARCHAR2(10 CHAR),
    link_status             VARCHAR2(20 CHAR) DEFAULT 'UNLINKED' NOT NULL,
    linked_transaction_id   NUMBER(19,0),
    category_method         VARCHAR2(20 CHAR),
    category_confidence     BINARY_DOUBLE
);

ALTER TABLE transactions ADD CONSTRAINT ck_transactions_source
    CHECK (source IN ('BANK','MANUAL'));

-- tarjeta de crédito excluida del MVP a propósito (ver conversación previa)
ALTER TABLE transactions ADD CONSTRAINT ck_transactions_payment_method
    CHECK (payment_method IN ('CASH','DEBIT'));

ALTER TABLE transactions ADD CONSTRAINT ck_transactions_link_status
    CHECK (link_status IN ('UNLINKED','AUTOMATIC','USER_CONFIRMED'));

ALTER TABLE transactions ADD CONSTRAINT ck_transactions_category_method
    CHECK (category_method IN ('MAPPING','KEYWORD_RULE','ML_MODEL','FALLBACK','USER_PROVIDED','USER_CORRECTED'));

ALTER TABLE transactions ADD CONSTRAINT ck_transactions_category_confidence
    CHECK (category_confidence IS NULL OR (category_confidence BETWEEN 0 AND 1));

ALTER TABLE transactions ADD CONSTRAINT fk_transactions_linked
    FOREIGN KEY (linked_transaction_id) REFERENCES transactions (id);

-- 3. Tabla nueva e independiente: porcentajes de referencia para el Motor de
--    Recomendaciones Presupuestarias. No toca transactions/users/currencies.
CREATE TABLE category_budget_targets (
    id                       NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY,
    country_code             VARCHAR2(2)   DEFAULT 'CL' NOT NULL,
    category                 VARCHAR2(50)  NOT NULL,
    recommended_percentage   NUMBER(5,2)   NOT NULL,
    source                   VARCHAR2(255),
    CONSTRAINT pk_category_budget_targets PRIMARY KEY (id),
    CONSTRAINT uk_cbt_country_category UNIQUE (country_code, category),
    CONSTRAINT ck_cbt_category CHECK (category IN
        ('FOOD','TRANSPORT','HOUSING','UTILITIES','ENTERTAINMENT',
         'HEALTH','EDUCATION','SHOPPING','OTHER_EXPENSE')),
    CONSTRAINT ck_cbt_percentage CHECK (recommended_percentage BETWEEN 0 AND 100)
);

-- Chile — fuente: INE, IX Encuesta de Presupuestos Familiares (EPF) 2022-2023.
-- Ver docs/plan-accion-motor-recomendaciones.md para el detalle del mapeo.
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'FOOD',          28.00, 'INE EPF 2022-2023: Alimentacion (19%) + Restaurantes fuera del hogar (9%)');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'HOUSING',       20.00, 'INE EPF 2022-2023: estimacion propia sobre Vivienda y servicios basicos (29%)');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'TRANSPORT',     14.00, 'INE EPF 2022-2023: Transporte');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'UTILITIES',      9.00, 'INE EPF 2022-2023: estimacion propia sobre Vivienda y servicios basicos (29%)');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'HEALTH',          7.00, 'INE EPF 2022-2023: Salud');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'EDUCATION',       6.00, 'INE EPF 2022-2023: Educacion');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'OTHER_EXPENSE',   6.00, 'INE EPF 2022-2023: Otros gastos');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'SHOPPING',        5.00, 'INE EPF 2022-2023: Vestimenta y calzado');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'ENTERTAINMENT',   5.00, 'INE EPF 2022-2023: Recreacion y cultura');
COMMIT;
