-- =====================================================================
-- Finance AI — Migración incremental #003
-- Aplica DESPUÉS de schema.sql + data.sql + 002_manual_entries_and_budget.sql
--
-- Resuelve el pendiente marcado en documentacion-tecnica.md: `users.financial_profile`
-- se sobreescribe en cada PUT /api/users/{id}/profile, así que hoy no se puede
-- reconstruir la evolución del perfil financiero de un usuario en el tiempo.
-- Esta tabla guarda una fila por cada actualización, sin tocar `users`.
-- =====================================================================

CREATE TABLE financial_profile_history (
    id                 NUMBER(19,0)       GENERATED BY DEFAULT AS IDENTITY,
    user_id            NUMBER(19,0)       NOT NULL,
    financial_profile  VARCHAR2(20 CHAR)  NOT NULL,
    profile_accuracy   BINARY_DOUBLE,
    recorded_at        TIMESTAMP(9)       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_financial_profile_history PRIMARY KEY (id),
    CONSTRAINT fk_fph_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_fph_profile CHECK (financial_profile IN ('SAVER','BALANCED','SPENDER','AT_RISK'))
);

-- Casi toda consulta sobre esta tabla es "dame la evolución de este usuario",
-- así que el índice va sobre user_id, igual que en transactions/recommendations.
CREATE INDEX idx_fph_user_id ON financial_profile_history (user_id);
