-- Finance AI — schema for Oracle Autonomous Database (ATP).
--
-- Run once, connected as the application schema user (not ADMIN), from
-- Database Actions > SQL, SQLcl or sqlplus:
--     @schema.sql
--     @data.sql
--
-- The column types mirror exactly what Hibernate maps the entities to, so the
-- app starts with spring.jpa.hibernate.ddl-auto=validate. If an entity changes,
-- change this file in the same commit or the app will refuse to start.

CREATE TABLE currencies (
    id            NUMBER(19,0)       GENERATED BY DEFAULT AS IDENTITY,
    name_currency VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT pk_currencies      PRIMARY KEY (id),
    CONSTRAINT uk_currencies_name UNIQUE (name_currency)
);

CREATE TABLE users (
    id                 NUMBER(19,0)       GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR2(255 CHAR) NOT NULL,
    email              VARCHAR2(255 CHAR) NOT NULL,
    -- BCrypt hash, never the plain password
    password           VARCHAR2(255 CHAR) NOT NULL,
    monthly_income     NUMBER(19,2),
    saving_frequency   VARCHAR2(20 CHAR),
    -- the three profile columns are written only by the external profiling app
    financial_profile  VARCHAR2(20 CHAR),
    profile_accuracy   BINARY_DOUBLE,
    profile_updated_at TIMESTAMP(9),
    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_saving_frequency
        CHECK (saving_frequency IN ('NEVER','RARELY','MONTHLY','BIWEEKLY','WEEKLY','DAILY')),
    CONSTRAINT ck_users_financial_profile
        CHECK (financial_profile IN ('SAVER','BALANCED','SPENDER','AT_RISK')),
    CONSTRAINT ck_users_profile_accuracy
        CHECK (profile_accuracy IS NULL OR (profile_accuracy >= 0 AND profile_accuracy <= 1))
);

-- logins are matched case-insensitively, so uniqueness has to be too
CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));

CREATE TABLE transactions (
    id               NUMBER(19,0)       GENERATED BY DEFAULT AS IDENTITY,
    description      VARCHAR2(255 CHAR),
    operation_number VARCHAR2(100 CHAR),
    -- always positive; the direction comes from the category
    amount           NUMBER(19,2)       NOT NULL,
    category         VARCHAR2(50 CHAR)  NOT NULL,
    -- "date" is a reserved word in Oracle
    transaction_date DATE               NOT NULL,
    currency_id      NUMBER(19,0)       NOT NULL,
    balance_after    NUMBER(19,2),
    user_id          NUMBER(19,0)       NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT fk_transactions_currency FOREIGN KEY (currency_id) REFERENCES currencies (id),
    CONSTRAINT fk_transactions_user     FOREIGN KEY (user_id)     REFERENCES users (id),
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_transactions_category CHECK (category IN
        ('FOOD','TRANSPORT','HOUSING','UTILITIES','ENTERTAINMENT','HEALTH','EDUCATION',
         'SHOPPING','SALARY','INVESTMENT','SAVINGS','OTHER_INCOME','OTHER_EXPENSE'))
);

CREATE INDEX idx_transactions_user_id ON transactions (user_id);

CREATE TABLE recommendations (
    id                    NUMBER(19,0)        GENERATED BY DEFAULT AS IDENTITY,
    text                  VARCHAR2(1000 CHAR) NOT NULL,
    generated_at          TIMESTAMP(9),
    profile_at_generation VARCHAR2(20 CHAR),
    user_id               NUMBER(19,0)        NOT NULL,
    CONSTRAINT pk_recommendations PRIMARY KEY (id),
    CONSTRAINT fk_recommendations_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_recommendations_profile
        CHECK (profile_at_generation IN ('SAVER','BALANCED','SPENDER','AT_RISK'))
);

CREATE INDEX idx_recommendations_user_id ON recommendations (user_id);
