-- =====================================================================
-- Finance AI — Presupuesto de referencia por categoría (Motor de
-- Recomendaciones Presupuestarias)
--
-- Tabla independiente: no toca transactions/users/currencies/recommendations
-- (que ya están validadas contra las entidades JPA con ddl-auto=validate).
--
-- Fuente de los porcentajes de Chile: Instituto Nacional de Estadísticas
-- (INE), IX Encuesta de Presupuestos Familiares (EPF) 2022-2023.
-- Dos categorías del sistema no calzan 1:1 con el desglose de la EPF y se
-- ajustaron a criterio propio (documentado abajo) — a revisar por el equipo.
-- =====================================================================

CREATE TABLE category_budget_targets (
    id                       NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY,
    country_code             VARCHAR2(2)   DEFAULT 'CL' NOT NULL,
    category                 VARCHAR2(50)  NOT NULL,
    recommended_percentage   NUMBER(5,2)   NOT NULL,
    source                   VARCHAR2(255),
    CONSTRAINT pk_category_budget_targets PRIMARY KEY (id),
    CONSTRAINT uk_cbt_country_category UNIQUE (country_code, category),
    CONSTRAINT ck_cbt_category CHECK (category IN
        ('FOOD','TRANSPORT','HOUSING','UTILITIES','ENTERTAINMENT',
         'HEALTH','EDUCATION','SHOPPING','OTHER_EXPENSE')),
    CONSTRAINT ck_cbt_percentage CHECK (recommended_percentage BETWEEN 0 AND 100)
);

-- Chile — suman 100% sobre el TOTAL DE GASTOS (type = EXPENSE), sin incluir
-- transferencias (type = TRANSFER) ni ahorro/inversión (type = SAVING).
--
-- HOUSING + UTILITIES = 29% en la EPF ("vivienda y servicios básicos"),
-- dividido acá 20/9 a criterio propio (la EPF no lo desglosa así).
-- FOOD = 19% (alimentación) + 9% (restaurantes fuera del hogar) = 28%,
-- porque el sistema no distingue esas dos sub-categorías.
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'FOOD',          28.00, 'INE EPF 2022-2023: Alimentacion (19%) + Restaurantes fuera del hogar (9%)');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'HOUSING',       20.00, 'INE EPF 2022-2023: estimacion propia sobre Vivienda y servicios basicos (29%)');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'TRANSPORT',     14.00, 'INE EPF 2022-2023: Transporte');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'UTILITIES',      9.00, 'INE EPF 2022-2023: estimacion propia sobre Vivienda y servicios basicos (29%)');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'HEALTH',          7.00, 'INE EPF 2022-2023: Salud');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'EDUCATION',       6.00, 'INE EPF 2022-2023: Educacion');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'OTHER_EXPENSE',   6.00, 'INE EPF 2022-2023: Otros gastos');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'SHOPPING',        5.00, 'INE EPF 2022-2023: Vestimenta y calzado');
INSERT INTO category_budget_targets (country_code, category, recommended_percentage, source) VALUES
    ('CL', 'ENTERTAINMENT',   5.00, 'INE EPF 2022-2023: Recreacion y cultura');
COMMIT;

-- Para agregar otro país a futuro: mismo INSERT, cambiando country_code y
-- los porcentajes. El servicio ya queda listo para filtrar por país una vez
-- que el usuario tenga un campo de país (hoy se asume 'CL' por defecto).
